export interface CatalogItem {
  key: string;
  description: string;
}

export interface Category {
  name: string;
  items: CatalogItem[];
}

export const CATEGORIES: Category[] = [
  {
    name: 'Claude / Session',
    items: [
      { key: 'claude:model', description: 'Model display name (Opus, Sonnet…)' },
      { key: 'claude:model-id', description: 'Full model identifier' },
      { key: 'claude:model-letter', description: 'First letter of model name' },
      { key: 'claude:version', description: 'Claude Code version' },
      { key: 'claude:session', description: 'Short session ID (8 chars)' },
      { key: 'claude:effort', description: 'Reasoning effort level' },
      { key: 'claude:effort-icon', description: 'Colored effort icon' },
      { key: 'claude:style', description: 'Output style name' },
    ],
  },
  {
    name: 'File System',
    items: [
      { key: 'fs:dir', description: 'Current directory name' },
      { key: 'fs:path', description: 'Full current directory path' },
      { key: 'fs:project', description: 'Project directory name' },
      { key: 'fs:project-path', description: 'Full project path' },
      { key: 'fs:home', description: 'Path with ~ for home' },
      { key: 'fs:relative', description: 'Relative to project root' },
      { key: 'fs:cwd', description: 'Raw working directory' },
    ],
  },
  {
    name: 'Git',
    items: [
      { key: 'git:branch', description: 'Current branch name' },
      { key: 'git:status', description: '✓ if clean, * if dirty' },
      { key: 'git:status-icon', description: 'Nerd font status icon' },
      { key: 'git:status-word', description: '"clean" or "dirty"' },
      { key: 'git:dirty', description: 'Colored dirty file summary' },
      { key: 'git:ahead', description: 'Commits ahead of upstream' },
      { key: 'git:behind', description: 'Commits behind upstream' },
      { key: 'git:ahead-behind', description: 'Both ahead and behind' },
      { key: 'git:staged', description: 'Staged file count' },
      { key: 'git:modified', description: 'Modified file count' },
      { key: 'git:untracked', description: 'Untracked file count' },
      { key: 'git:stash', description: 'Stash count' },
      { key: 'git:commit', description: 'Short commit hash' },
      { key: 'git:tag', description: 'Latest tag' },
      { key: 'git:repo', description: 'Repository name' },
      { key: 'git:repo-branch', description: 'repo:branch format' },
      { key: 'git:user', description: 'Git user name' },
      { key: 'git:email', description: 'Git user email' },
    ],
  },
  {
    name: 'Context Window',
    items: [
      { key: 'ctx:percent', description: 'Context used percentage' },
      { key: 'ctx:remaining', description: 'Remaining percentage' },
      { key: 'ctx:tokens', description: 'Used/total tokens' },
      { key: 'ctx:bar', description: 'Progress bar (10 chars)' },
      { key: 'ctx:icon', description: 'Colored usage circle' },
      { key: 'ctx:in', description: 'Input tokens' },
      { key: 'ctx:out', description: 'Output tokens' },
      { key: 'ctx:size', description: 'Window size' },
      { key: 'ctx:used-tokens', description: 'Total used tokens' },
    ],
  },
  {
    name: 'Cost / Duration',
    items: [
      { key: 'cost:total', description: 'Total cost in USD' },
      { key: 'cost:total-cents', description: 'Total cost in cents' },
      { key: 'cost:duration', description: 'Session duration' },
      { key: 'cost:api', description: 'API call duration' },
      { key: 'cost:lines', description: 'Net lines changed' },
      { key: 'cost:lines-added', description: 'Lines added' },
      { key: 'cost:lines-removed', description: 'Lines removed' },
      { key: 'cost:lines-both', description: '+added −removed' },
    ],
  },
  {
    name: 'Rate Limits',
    items: [
      { key: 'usage:5h', description: '5-hour limit percentage' },
      { key: 'usage:week', description: '7-day limit percentage' },
      { key: 'usage:5h-bar', description: '5-hour progress bar' },
      { key: 'usage:week-bar', description: '7-day progress bar' },
      { key: 'usage:5h-icon', description: '5-hour colored circle' },
      { key: 'usage:week-icon', description: '7-day colored circle' },
      { key: 'usage:5h-reset', description: 'Time until 5h reset' },
      { key: 'usage:week-reset', description: 'Time until 7d reset' },
      { key: 'usage:5h-pace', description: '5-hour pace delta' },
      { key: 'usage:week-pace', description: '7-day pace delta' },
      { key: 'usage:5h-pace-icon', description: '5-hour pace icon' },
      { key: 'usage:week-pace-icon', description: '7-day pace icon' },
    ],
  },
  {
    name: 'Environment',
    items: [
      { key: 'env:node', description: 'Node.js version' },
      { key: 'env:bun', description: 'Bun version' },
      { key: 'env:python', description: 'Python version' },
      { key: 'env:rust', description: 'Rust version' },
      { key: 'env:go', description: 'Go version' },
      { key: 'env:user', description: 'Current username' },
      { key: 'env:hostname', description: 'System hostname' },
      { key: 'env:shell', description: 'Shell name' },
      { key: 'env:os', description: 'Operating system' },
      { key: 'env:arch', description: 'CPU architecture' },
      { key: 'env:cpus', description: 'CPU count' },
      { key: 'env:memory', description: 'Total memory' },
    ],
  },
  {
    name: 'Time',
    items: [
      { key: 'time:now', description: 'HH:MM (24h)' },
      { key: 'time:12h', description: 'HH:MM AM/PM' },
      { key: 'time:seconds', description: 'HH:MM:SS' },
      { key: 'time:date', description: 'Short date (Mar 20)' },
      { key: 'time:full', description: 'ISO date (YYYY-MM-DD)' },
      { key: 'time:weekday', description: 'Short weekday' },
      { key: 'time:elapsed', description: 'Session elapsed time' },
    ],
  },
  {
    name: 'Separators',
    items: [
      { key: 'sep:pipe', description: '|' },
      { key: 'sep:arrow', description: '→' },
      { key: 'sep:arrow-left', description: '←' },
      { key: 'sep:chevron', description: '›' },
      { key: 'sep:dot', description: '•' },
      { key: 'sep:middot', description: '·' },
      { key: 'sep:dash', description: '—' },
      { key: 'sep:slash', description: '/' },
      { key: 'sep:colon', description: ':' },
      { key: 'sep:space', description: '(space)' },
      { key: 'sep:none', description: '(empty)' },
      { key: 'sep:powerline', description: '' },
      { key: 'sep:powerline-left', description: '' },
      { key: 'sep:newline', description: '(new line)' },
      { key: 'sep:diamond', description: '◇' },
      { key: 'sep:bullet', description: '◦' },
      { key: 'sep:star', description: '★' },
    ],
  },
  {
    name: 'Icons (Nerd Font)',
    items: [
      { key: 'nerd:folder', description: 'Folder' },
      { key: 'nerd:folder-open', description: 'Open folder' },
      { key: 'nerd:file', description: 'File' },
      { key: 'nerd:file-code', description: 'Code file' },
      { key: 'nerd:branch', description: 'Branch' },
      { key: 'nerd:commit', description: 'Commit' },
      { key: 'nerd:tag', description: 'Tag' },
      { key: 'nerd:repo', description: 'Repository' },
      { key: 'nerd:rocket', description: 'Rocket' },
      { key: 'nerd:sparkle', description: 'Sparkle' },
      { key: 'nerd:lightning', description: 'Lightning' },
      { key: 'nerd:fire', description: 'Fire' },
      { key: 'nerd:star', description: 'Star' },
      { key: 'nerd:heart', description: 'Heart' },
      { key: 'nerd:check', description: 'Check mark' },
      { key: 'nerd:terminal', description: 'Terminal' },
      { key: 'nerd:gear', description: 'Gear' },
      { key: 'nerd:clock', description: 'Clock' },
      { key: 'nerd:lock', description: 'Lock' },
      { key: 'nerd:code', description: 'Code' },
      { key: 'nerd:database', description: 'Database' },
      { key: 'nerd:cloud', description: 'Cloud' },
      { key: 'nerd:home', description: 'Home' },
      { key: 'nerd:user', description: 'User' },
    ],
  },
];

export const STYLES = [
  { key: '(none)', description: 'Remove style' },
  // Colors
  { key: 'red', description: 'Red' },
  { key: 'green', description: 'Green' },
  { key: 'blue', description: 'Blue' },
  { key: 'yellow', description: 'Yellow' },
  { key: 'magenta', description: 'Magenta' },
  { key: 'cyan', description: 'Cyan' },
  { key: 'white', description: 'White' },
  { key: 'gray', description: 'Gray' },
  // Bright
  { key: 'bright-red', description: 'Bright red' },
  { key: 'bright-green', description: 'Bright green' },
  { key: 'bright-blue', description: 'Bright blue' },
  { key: 'bright-yellow', description: 'Bright yellow' },
  { key: 'bright-magenta', description: 'Bright magenta' },
  { key: 'bright-cyan', description: 'Bright cyan' },
  // Attributes
  { key: 'bold', description: 'Bold' },
  { key: 'dim', description: 'Dim' },
  { key: 'italic', description: 'Italic' },
  { key: 'underline', description: 'Underline' },
  { key: 'inverse', description: 'Inverse' },
  // Combined
  { key: 'bold:red', description: 'Bold red' },
  { key: 'bold:green', description: 'Bold green' },
  { key: 'bold:blue', description: 'Bold blue' },
  { key: 'bold:yellow', description: 'Bold yellow' },
  { key: 'bold:magenta', description: 'Bold magenta' },
  { key: 'bold:cyan', description: 'Bold cyan' },
  { key: 'bold:white', description: 'Bold white' },
  { key: 'dim:white', description: 'Dim white' },
  { key: 'dim:gray', description: 'Dim gray' },
];
